// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cards.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/lib/pq"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (id, deck_id, front, back, due_at)
VALUES ($1, $2, $3, $4, NOW())
RETURNING id, deck_id, front, back, ease_factor, interval_days, repetitions, due_at, created_at
`

type CreateCardParams struct {
	ID     uuid.UUID `json:"id"`
	DeckID uuid.UUID `json:"deck_id"`
	Front  string    `json:"front"`
	Back   string    `json:"back"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRowContext(ctx, createCard,
		arg.ID,
		arg.DeckID,
		arg.Front,
		arg.Back,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.DueAt,
		&i.CreatedAt,
	)
	return i, err
}

const createManyCards = `-- name: CreateManyCards :exec
INSERT INTO cards (id, deck_id, front, back, due_at)
SELECT
  unnest($1::uuid[]),
  unnest($2::uuid[]),
  unnest($3::text[]),
  unnest($4::text[]),
  NOW()
`

type CreateManyCardsParams struct {
	Column1 []uuid.UUID `json:"column_1"`
	Column2 []uuid.UUID `json:"column_2"`
	Column3 []string    `json:"column_3"`
	Column4 []string    `json:"column_4"`
}

func (q *Queries) CreateManyCards(ctx context.Context, arg CreateManyCardsParams) error {
	_, err := q.db.ExecContext(ctx, createManyCards,
		pq.Array(arg.Column1),
		pq.Array(arg.Column2),
		pq.Array(arg.Column3),
		pq.Array(arg.Column4),
	)
	return err
}

const deleteCard = `-- name: DeleteCard :exec
DELETE FROM cards WHERE id = $1
`

func (q *Queries) DeleteCard(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteCard, id)
	return err
}

const getCardByID = `-- name: GetCardByID :one
SELECT id, deck_id, front, back, ease_factor, interval_days, repetitions, due_at, created_at FROM cards
WHERE id = $1
`

func (q *Queries) GetCardByID(ctx context.Context, id uuid.UUID) (Card, error) {
	row := q.db.QueryRowContext(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.DeckID,
		&i.Front,
		&i.Back,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.Repetitions,
		&i.DueAt,
		&i.CreatedAt,
	)
	return i, err
}

const getCardsByDeck = `-- name: GetCardsByDeck :many
SELECT id, deck_id, front, back, ease_factor, interval_days, repetitions, due_at, created_at FROM cards
WHERE deck_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetCardsByDeck(ctx context.Context, deckID uuid.UUID) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getCardsByDeck, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.DueAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDueCards = `-- name: GetDueCards :many
SELECT id, deck_id, front, back, ease_factor, interval_days, repetitions, due_at, created_at FROM cards
WHERE deck_id IN (
    SELECT id FROM decks WHERE user_id = $1
)
AND ($2::uuid IS NULL OR deck_id = $2)
AND due_at <= $3
ORDER BY due_at ASC
LIMIT $4
`

type GetDueCardsParams struct {
	UserID uuid.UUID     `json:"user_id"`
	DeckID uuid.NullUUID `json:"deck_id"`
	DueAt  time.Time     `json:"due_at"`
	Limit  int32         `json:"limit"`
}

func (q *Queries) GetDueCards(ctx context.Context, arg GetDueCardsParams) ([]Card, error) {
	rows, err := q.db.QueryContext(ctx, getDueCards,
		arg.UserID,
		arg.DeckID,
		arg.DueAt,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Card
	for rows.Next() {
		var i Card
		if err := rows.Scan(
			&i.ID,
			&i.DeckID,
			&i.Front,
			&i.Back,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.Repetitions,
			&i.DueAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCardScheduling = `-- name: UpdateCardScheduling :exec
UPDATE cards
SET
    interval_days = $2,
    repetitions   = $3,
    ease_factor   = $4,
    due_at        = $5
WHERE id = $1
`

type UpdateCardSchedulingParams struct {
	ID           uuid.UUID `json:"id"`
	IntervalDays int32     `json:"interval_days"`
	Repetitions  int32     `json:"repetitions"`
	EaseFactor   float64   `json:"ease_factor"`
	DueAt        time.Time `json:"due_at"`
}

func (q *Queries) UpdateCardScheduling(ctx context.Context, arg UpdateCardSchedulingParams) error {
	_, err := q.db.ExecContext(ctx, updateCardScheduling,
		arg.ID,
		arg.IntervalDays,
		arg.Repetitions,
		arg.EaseFactor,
		arg.DueAt,
	)
	return err
}
