// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createDeck = `-- name: CreateDeck :one
INSERT INTO decks (id, user_id, name, description, category)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, parent_id, name, description, created_at, category
`

type CreateDeckParams struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Category    sql.NullString `json:"category"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (Deck, error) {
	row := q.db.QueryRowContext(ctx, createDeck,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Category,
	)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Category,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :exec
DELETE FROM decks WHERE id = $1
`

func (q *Queries) DeleteDeck(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteDeck, id)
	return err
}

const getCategoriesByUser = `-- name: GetCategoriesByUser :many
SELECT DISTINCT category
FROM decks
WHERE user_id = $1
  AND category IS NOT NULL
  AND category != ''
ORDER BY category ASC
`

func (q *Queries) GetCategoriesByUser(ctx context.Context, userID uuid.UUID) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getCategoriesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []sql.NullString
	for rows.Next() {
		var category sql.NullString
		if err := rows.Scan(&category); err != nil {
			return nil, err
		}
		items = append(items, category)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeckByID = `-- name: GetDeckByID :one
SELECT id, user_id, parent_id, name, description, created_at, category FROM decks
WHERE id = $1
`

func (q *Queries) GetDeckByID(ctx context.Context, id uuid.UUID) (Deck, error) {
	row := q.db.QueryRowContext(ctx, getDeckByID, id)
	var i Deck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ParentID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.Category,
	)
	return i, err
}

const getDecksByUser = `-- name: GetDecksByUser :many
SELECT id, user_id, parent_id, name, description, created_at, category FROM decks
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetDecksByUser(ctx context.Context, userID uuid.UUID) ([]Deck, error) {
	rows, err := q.db.QueryContext(ctx, getDecksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Deck
	for rows.Next() {
		var i Deck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ParentID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
