// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createReviewLog = `-- name: CreateReviewLog :exec
INSERT INTO review_logs (id, card_id, user_id, rating, interval_days, ease_factor, response_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateReviewLogParams struct {
	ID           uuid.UUID     `json:"id"`
	CardID       uuid.UUID     `json:"card_id"`
	UserID       uuid.UUID     `json:"user_id"`
	Rating       int32         `json:"rating"`
	IntervalDays int32         `json:"interval_days"`
	EaseFactor   float64       `json:"ease_factor"`
	ResponseMs   sql.NullInt32 `json:"response_ms"`
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) error {
	_, err := q.db.ExecContext(ctx, createReviewLog,
		arg.ID,
		arg.CardID,
		arg.UserID,
		arg.Rating,
		arg.IntervalDays,
		arg.EaseFactor,
		arg.ResponseMs,
	)
	return err
}

const getCurrentStreak = `-- name: GetCurrentStreak :one
WITH daily_reviews AS (
    SELECT DISTINCT DATE(reviewed_at) AS review_date
    FROM review_logs
    WHERE user_id = $1
),
streak AS (
    SELECT review_date,
           review_date - (ROW_NUMBER() OVER (ORDER BY review_date))::int AS grp
    FROM daily_reviews
)
SELECT COUNT(*)::int AS streak
FROM streak
WHERE grp = (
    SELECT grp FROM streak
    WHERE review_date = CURRENT_DATE
       OR review_date = CURRENT_DATE - 1
    ORDER BY review_date DESC
    LIMIT 1
)
`

func (q *Queries) GetCurrentStreak(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRowContext(ctx, getCurrentStreak, userID)
	var streak int32
	err := row.Scan(&streak)
	return streak, err
}

const getReviewLogsByUser = `-- name: GetReviewLogsByUser :many
SELECT id, card_id, user_id, rating, interval_days, ease_factor, response_ms, reviewed_at FROM review_logs
WHERE user_id = $1
ORDER BY reviewed_at DESC
LIMIT $2
`

type GetReviewLogsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetReviewLogsByUser(ctx context.Context, arg GetReviewLogsByUserParams) ([]ReviewLog, error) {
	rows, err := q.db.QueryContext(ctx, getReviewLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewLog
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.Rating,
			&i.IntervalDays,
			&i.EaseFactor,
			&i.ResponseMs,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyStatsByDeck = `-- name: GetWeeklyStatsByDeck :many
SELECT
    d.name                                                           AS deck_name,
    COUNT(*)::int                                                    AS total_reviewed,
    COUNT(*) FILTER (WHERE rl.rating >= 3)::int                     AS total_correct
FROM review_logs rl
JOIN cards  c ON c.id  = rl.card_id
JOIN decks  d ON d.id  = c.deck_id
WHERE rl.user_id    = $1
  AND rl.reviewed_at >= NOW() - INTERVAL '7 days'
GROUP BY d.id, d.name
ORDER BY total_reviewed DESC
`

type GetWeeklyStatsByDeckRow struct {
	DeckName      string `json:"deck_name"`
	TotalReviewed int32  `json:"total_reviewed"`
	TotalCorrect  int32  `json:"total_correct"`
}

func (q *Queries) GetWeeklyStatsByDeck(ctx context.Context, userID uuid.UUID) ([]GetWeeklyStatsByDeckRow, error) {
	rows, err := q.db.QueryContext(ctx, getWeeklyStatsByDeck, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetWeeklyStatsByDeckRow
	for rows.Next() {
		var i GetWeeklyStatsByDeckRow
		if err := rows.Scan(&i.DeckName, &i.TotalReviewed, &i.TotalCorrect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklySummary = `-- name: GetWeeklySummary :one
SELECT
    COUNT(*)::int                                                    AS total_reviewed,
    COUNT(*) FILTER (WHERE rating >= 3)::int                        AS total_correct,
    COUNT(DISTINCT DATE(reviewed_at))::int                          AS days_studied,
    COUNT(DISTINCT card_id)::int                                     AS unique_cards
FROM review_logs
WHERE user_id    = $1
  AND reviewed_at >= NOW() - INTERVAL '7 days'
`

type GetWeeklySummaryRow struct {
	TotalReviewed int32 `json:"total_reviewed"`
	TotalCorrect  int32 `json:"total_correct"`
	DaysStudied   int32 `json:"days_studied"`
	UniqueCards   int32 `json:"unique_cards"`
}

func (q *Queries) GetWeeklySummary(ctx context.Context, userID uuid.UUID) (GetWeeklySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getWeeklySummary, userID)
	var i GetWeeklySummaryRow
	err := row.Scan(
		&i.TotalReviewed,
		&i.TotalCorrect,
		&i.DaysStudied,
		&i.UniqueCards,
	)
	return i, err
}
