// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const addDeckToSession = `-- name: AddDeckToSession :exec
INSERT INTO session_decks (session_id, deck_id)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddDeckToSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	DeckID    uuid.UUID `json:"deck_id"`
}

func (q *Queries) AddDeckToSession(ctx context.Context, arg AddDeckToSessionParams) error {
	_, err := q.db.ExecContext(ctx, addDeckToSession, arg.SessionID, arg.DeckID)
	return err
}

const createStudySession = `-- name: CreateStudySession :one
INSERT INTO study_sessions (id, user_id, name)
VALUES ($1, $2, $3)
RETURNING id, user_id, name, created_at
`

type CreateStudySessionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) CreateStudySession(ctx context.Context, arg CreateStudySessionParams) (StudySession, error) {
	row := q.db.QueryRowContext(ctx, createStudySession, arg.ID, arg.UserID, arg.Name)
	var i StudySession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteStudySession = `-- name: DeleteStudySession :exec
DELETE FROM study_sessions WHERE id = $1
`

func (q *Queries) DeleteStudySession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStudySession, id)
	return err
}

const getSessionDeckIDs = `-- name: GetSessionDeckIDs :many
SELECT deck_id FROM session_decks WHERE session_id = $1
`

func (q *Queries) GetSessionDeckIDs(ctx context.Context, sessionID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getSessionDeckIDs, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var deck_id uuid.UUID
		if err := rows.Scan(&deck_id); err != nil {
			return nil, err
		}
		items = append(items, deck_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStudySessionByID = `-- name: GetStudySessionByID :one
SELECT s.id, s.user_id, s.name, s.created_at,
       ARRAY_AGG(sd.deck_id) FILTER (WHERE sd.deck_id IS NOT NULL) AS deck_ids
FROM study_sessions s
LEFT JOIN session_decks sd ON sd.session_id = s.id
WHERE s.id = $1
GROUP BY s.id
`

type GetStudySessionByIDRow struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Name      string      `json:"name"`
	CreatedAt time.Time   `json:"created_at"`
	DeckIds   interface{} `json:"deck_ids"`
}

func (q *Queries) GetStudySessionByID(ctx context.Context, id uuid.UUID) (GetStudySessionByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getStudySessionByID, id)
	var i GetStudySessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
		&i.DeckIds,
	)
	return i, err
}

const getStudySessionsByUser = `-- name: GetStudySessionsByUser :many
SELECT s.id, s.user_id, s.name, s.created_at,
       ARRAY_AGG(sd.deck_id) FILTER (WHERE sd.deck_id IS NOT NULL) AS deck_ids
FROM study_sessions s
LEFT JOIN session_decks sd ON sd.session_id = s.id
WHERE s.user_id = $1
GROUP BY s.id
ORDER BY s.created_at DESC
`

type GetStudySessionsByUserRow struct {
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Name      string      `json:"name"`
	CreatedAt time.Time   `json:"created_at"`
	DeckIds   interface{} `json:"deck_ids"`
}

func (q *Queries) GetStudySessionsByUser(ctx context.Context, userID uuid.UUID) ([]GetStudySessionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getStudySessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStudySessionsByUserRow
	for rows.Next() {
		var i GetStudySessionsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
			&i.DeckIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeDeckFromSession = `-- name: RemoveDeckFromSession :exec
DELETE FROM session_decks
WHERE session_id = $1 AND deck_id = $2
`

type RemoveDeckFromSessionParams struct {
	SessionID uuid.UUID `json:"session_id"`
	DeckID    uuid.UUID `json:"deck_id"`
}

func (q *Queries) RemoveDeckFromSession(ctx context.Context, arg RemoveDeckFromSessionParams) error {
	_, err := q.db.ExecContext(ctx, removeDeckFromSession, arg.SessionID, arg.DeckID)
	return err
}

const replaceSessionDecks = `-- name: ReplaceSessionDecks :exec
DELETE FROM session_decks WHERE session_id = $1
`

func (q *Queries) ReplaceSessionDecks(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, replaceSessionDecks, sessionID)
	return err
}

const updateStudySessionName = `-- name: UpdateStudySessionName :exec
UPDATE study_sessions
SET name = $2
WHERE id = $1
`

type UpdateStudySessionNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

func (q *Queries) UpdateStudySessionName(ctx context.Context, arg UpdateStudySessionNameParams) error {
	_, err := q.db.ExecContext(ctx, updateStudySessionName, arg.ID, arg.Name)
	return err
}
