// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Card struct {
	ID           uuid.UUID `json:"id"`
	DeckID       uuid.UUID `json:"deck_id"`
	Front        string    `json:"front"`
	Back         string    `json:"back"`
	EaseFactor   float64   `json:"ease_factor"`
	IntervalDays int32     `json:"interval_days"`
	Repetitions  int32     `json:"repetitions"`
	DueAt        time.Time `json:"due_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type CardTag struct {
	CardID uuid.UUID `json:"card_id"`
	TagID  uuid.UUID `json:"tag_id"`
}

type Deck struct {
	ID          uuid.UUID      `json:"id"`
	UserID      uuid.UUID      `json:"user_id"`
	ParentID    uuid.NullUUID  `json:"parent_id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type ReviewLog struct {
	ID           uuid.UUID     `json:"id"`
	CardID       uuid.UUID     `json:"card_id"`
	UserID       uuid.UUID     `json:"user_id"`
	Rating       int32         `json:"rating"`
	IntervalDays int32         `json:"interval_days"`
	EaseFactor   float64       `json:"ease_factor"`
	ResponseMs   sql.NullInt32 `json:"response_ms"`
	ReviewedAt   time.Time     `json:"reviewed_at"`
}

type Tag struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

type User struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	Name         string    `json:"name"`
	CreatedAt    time.Time `json:"created_at"`
	PasswordHash string    `json:"password_hash"`
}
