// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createReviewLog = `-- name: CreateReviewLog :exec
INSERT INTO review_logs (id, card_id, user_id, rating, interval_days, ease_factor, response_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateReviewLogParams struct {
	ID           uuid.UUID     `json:"id"`
	CardID       uuid.UUID     `json:"card_id"`
	UserID       uuid.UUID     `json:"user_id"`
	Rating       int32         `json:"rating"`
	IntervalDays int32         `json:"interval_days"`
	EaseFactor   float64       `json:"ease_factor"`
	ResponseMs   sql.NullInt32 `json:"response_ms"`
}

func (q *Queries) CreateReviewLog(ctx context.Context, arg CreateReviewLogParams) error {
	_, err := q.db.ExecContext(ctx, createReviewLog,
		arg.ID,
		arg.CardID,
		arg.UserID,
		arg.Rating,
		arg.IntervalDays,
		arg.EaseFactor,
		arg.ResponseMs,
	)
	return err
}

const getReviewLogsByUser = `-- name: GetReviewLogsByUser :many
SELECT id, card_id, user_id, rating, interval_days, ease_factor, response_ms, reviewed_at FROM review_logs
WHERE user_id = $1
ORDER BY reviewed_at DESC
LIMIT $2
`

type GetReviewLogsByUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

func (q *Queries) GetReviewLogsByUser(ctx context.Context, arg GetReviewLogsByUserParams) ([]ReviewLog, error) {
	rows, err := q.db.QueryContext(ctx, getReviewLogsByUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReviewLog
	for rows.Next() {
		var i ReviewLog
		if err := rows.Scan(
			&i.ID,
			&i.CardID,
			&i.UserID,
			&i.Rating,
			&i.IntervalDays,
			&i.EaseFactor,
			&i.ResponseMs,
			&i.ReviewedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
